### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#86]
- [ ] Use [`real_coordinates`](https://github.com/minetest/minetest/commit/5e7004e7af)
- [ ] Change the formspec layout using [`style`](https://github.com/minetest/minetest/commit/ec3795a55c) and 9-sliced background
- [ ] Add an API for custom formspec styles
- [ ] Improve `craftguide.register_craft()`
- [ ] Display recipes in-world: https://github.com/minetest-mods/craftguide/issues/56

**Comment by edenprojectde** [comment]
is there a possibility to add keybindings for r (Recipe) and u (Used in)?

**Comment by kilbith** [comment]
> is there a possibility to add keybindings for r (Recipe) and u (Used in)?

Great idea, but needs https://github.com/minetest/minetest/pull/8679 to be merged first.

**Comment by MoNTE48** [comment]
Is it possible to split init.lua into several files in order to move the API in the HUD to another location?
A mod with 1 file on more than 2000 lines is complicated enough to modify and transfer new changes after that.

**Comment by kilbith** [comment]
No, this won't be done
